version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "15.2"  # Use your Xcode version
    steps:
      - checkout  # Pulls the code from your GitHub repository

      - run:
          name: Check Ruby version
          command: ruby -v
          
      - run:
          name: Install Bundler
          command: gem install bundler --user-install

     # Install dependencies
      - run:
          name: Install Dependencies
          command: bundle install

      - run:
          name: Build and Test
          command: xcodebuild test -project FirstCICDDemo.xcodeproj -scheme FirstCICDDemo -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
